# Generated by Django 5.2.12 on 2026-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_safe_cache_dropbox_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersetting',
            name='dropbox_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='dropbox_url_cached',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cached Dropbox Image URL'),
        ),
        migrations.AddField(
            model_name='bannersetting',
            name='dropbox_url_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cached Image URL Expiry'),
        ),
        migrations.AddField(
            model_name='category',
            name='dropbox_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='dropbox_url_cached',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cached Dropbox Image URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='dropbox_url_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cached Image URL Expiry'),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='favicon_dropbox_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='favicon_dropbox_url_cached',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cached Dropbox Favicon URL'),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='favicon_dropbox_url_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cached Favicon URL Expiry'),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='logo_dropbox_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='logo_dropbox_url_cached',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cached Dropbox Logo URL'),
        ),
        migrations.AddField(
            model_name='navbarsetting',
            name='logo_dropbox_url_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cached Logo URL Expiry'),
        ),
    ]
