# Generated by Django 5.2.12 on 2026-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bannersetting_dropbox_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='BoosterNotes', max_length=100, verbose_name='App Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='pwa/', verbose_name='App Icon')),
                ('icon_dropbox_path', models.CharField(blank=True, max_length=500, null=True)),
                ('icon_dropbox_url_cached', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Cached Dropbox Icon URL')),
                ('icon_dropbox_url_expires', models.DateTimeField(blank=True, null=True, verbose_name='Cached Icon URL Expiry')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enable Install Prompt')),
            ],
            options={
                'verbose_name': 'PWA Setting',
                'verbose_name_plural': 'PWA Settings',
            },
        ),
    ]
