# Generated by Django 5.2.12 on 2026-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_pwasettings_elibrarymodel_dropbox_thumbnail_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(blank=True, max_length=200, verbose_name='Razorpay Key ID')),
                ('key_secret', models.CharField(blank=True, max_length=200, verbose_name='Razorpay Key Secret')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Razorpay Setting',
                'verbose_name_plural': 'Razorpay Settings',
            },
        ),
    ]
